### ISSUE TITLE
Fabric loader crash

### ISSUE THREAD

**Issue by Badr69420** [HopiHopy/PojavZenithHorizon#53]
### Problem Description

When i use the latest fabric loader (0.15.11)
It crashes but when i use (0.15.10) it does not crash, how do i fix this?

### Logs/Screenshots or Videos

[latestlog.txt](https://github.com/user-attachments/files/16026339/latestlog.txt)

### Steps to Reproduce
Open launcher, download fabric latest version, clik play snd it crashes.
```markdown
.
```

### Expected Behavior

I exepected to launch the game

### Android Version

13

### Pojav Zenith Horizon Version

1.2.3

### Additional Information

```markdown
- Device Model:
- CPU Architecture:
- GPU Information:
Oppo a96
Arm64
Adreno 610
```

### This issue has not been reported by anyone else yet

- [x] I have checked the issues and have not found any similar reports

**Comment by HopiHopy** [comment]
@Badr69420 The log file reports that some dependency libraries are either corrupted or missing. I infer that your game did not download completely due to some issues. Therefore, please try deleting your game files, game dependency libraries, or uninstalling and reinstalling the software. Then, reinstall your game and check if the issue still persists when you launch it.

**Comment by Badr69420** [comment]
Thanks, please fix the dowload instace its not downloading all the file for like:optifine fabric etc.. that is why it crashes, i fixed it thanks to the fabric jar that i installed because it didnt install fabric fully so...
